# Generated by Django 3.2.14 on 2022-07-29 19:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviewFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='%Y/%m/%d/%H/%M/')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.contentfile')),
            ],
            options={
                'verbose_name': 'Preview File',
                'verbose_name_plural': 'Preview Files',
                'ordering': ['file'],
            },
        ),
    ]
