user_list = [
    {
        "first_name": "Bill",
        "last_name": "Palmer",
        "username": "billpalmer",
        "email": "bill.palmer@partsunlimit.com",
        "position": "VP of IT Operations",
        "group": "phoenix-managers",
        "is_staff": True,
        "is_superuser": True,
    },
    {
        "first_name": "Dick",
        "last_name": "Landry",
        "username": "dicklandry",
        "email": "dick.landry@partsunlimit.com",
        "position": "CFO",
        "group": "phoenix-contributors",
        "is_staff": False,
        "is_superuser": False,
    },
    {
        "first_name": "Sarah",
        "last_name": "Moulton",
        "username": "sarahmoulton",
        "email": "sarah.moulton@partsunlimit.com",
        "position": "SVP of Retail Operations",
        "group": "phoenix-consumers",
        "is_staff": False,
        "is_superuser": False,
    },
    {
        "first_name": "Maggie",
        "last_name": "Lee",
        "username": "maggielee",
        "email": "maggie.lee@partsunlimit.com",
        "position": "Senior Director of Retail Program Mgmt",
        "group": "phoenix-consumers",
        "is_staff": False,
        "is_superuser": False,
    },
    {
        "first_name": "Wes",
        "last_name": "Davis",
        "username": "wesdavis",
        "email": "wes.davis@partsunlimit.com",
        "position": "Directory of Distributed Technology Operations",
        "group": "phoenix-contributors",
        "is_staff": False,
        "is_superuser": False,
    },
    {
        "first_name": "Brent",
        "last_name": "Geller",
        "username": "brentgeller",
        "email": "brent.geller@partsunlimit.com",
        "position": "Lead Engineer",
        "group": "phoenix-contributors",
        "is_staff": True,
        "is_superuser": True,
    },
    {
        "first_name": "Patty",
        "last_name": "McKee",
        "username": "pattymckee",
        "email": "patty.mckee@partsunlimit.com",
        "position": "Director of IT Service Support",
        "group": "phoenix-editors",
        "is_staff": False,
        "is_superuser": False,
    },
    {
        "first_name": "John",
        "last_name": "Pesche",
        "username": "johnpesche",
        "email": "john.pesche@partsunlimit.com",
        "position": "Chief Information Security Officer",
        "group": "phoenix-contributors",
        "is_staff": False,
        "is_superuser": False,
    },
    {
        "first_name": "Chris",
        "last_name": "Allers",
        "username": "chrisallers",
        "email": "chris.allers@partsunlimit.com",
        "position": "VP of Application Development",
        "group": "phoenix-editors",
        "is_staff": False,
        "is_superuser": False,
    },
]
