# Generated by Django 3.2.14 on 2022-07-29 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import repo.abstract_models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('file', repo.abstract_models.UUIDNamedFileField(max_length=260, upload_to='%Y/%m/%d/%H/%M/')),
                ('version', models.CharField(default='1.0', max_length=12)),
                ('is_indexed', models.BooleanField(default=False)),
                ('index_error', models.TextField(blank=True, null=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('version_type', models.CharField(choices=[('major', 'major'), ('minor', 'minor')], default='minor', max_length=30, verbose_name='Version Type')),
            ],
            options={
                'verbose_name': 'Content File',
                'verbose_name_plural': 'Content Files',
                'ordering': ['parent__name'],
            },
        ),
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Content Type',
                'verbose_name_plural': 'Content Types',
                'ordering': ['name'],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('orig_name', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_system', models.BooleanField(default=False, verbose_name='System Folder')),
                ('orig_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_orig_parent', to='repo.folder')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_parent', to='repo.folder')),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
                'ordering': ['name', 'parent__name'],
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('orig_name', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrphanContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('content_file_path', models.CharField(max_length=255)),
                ('orig_parent_type', models.CharField(choices=[('content_file', 'content_file'), ('preview_file', 'preview_file')], max_length=30)),
                ('orig_parent_path', models.TextField()),
            ],
            options={
                'verbose_name': 'Orphan Content File',
                'verbose_name_plural': 'Orphan Content Files',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('orig_name', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('icon', models.ImageField(upload_to='uploads/project_icons/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('access', models.CharField(choices=[('open', 'Open'), ('private', 'Private'), ('public', 'Public')], default='public', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('consumer_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_consumer_group', to='auth.group')),
                ('contributor_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_contributor_group', to='auth.group')),
                ('editor_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_editor_group', to='auth.group')),
                ('home_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repo.folder')),
                ('manager_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_manager_group', to='auth.group')),
                ('members', models.ManyToManyField(related_name='project_members', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('slack', models.CharField(blank=True, max_length=50, null=True)),
                ('skype', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedin_profile_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn URL')),
                ('home_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_home_folder', to='repo.folder')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repo.organization')),
                ('trashcan_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_trashcan_folder', to='repo.folder')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('orig_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('creater', models.CharField(blank=True, max_length=255, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('contributor', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('dctype', models.CharField(blank=True, max_length=255, null=True)),
                ('format', models.CharField(blank=True, max_length=255, null=True)),
                ('identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('relation', models.CharField(blank=True, max_length=255, null=True)),
                ('coverage', models.TextField(blank=True, null=True)),
                ('rights', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('extension', models.CharField(blank=True, max_length=20, null=True)),
                ('content_files', models.ManyToManyField(blank=True, to='repo.ContentFile')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repo.contenttype')),
                ('orig_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_orig_parent', to='repo.folder')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_parent', to='repo.folder')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['name'],
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='ContentFileIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('content_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.contentfile')),
            ],
            options={
                'verbose_name': 'ContentFile Index',
                'verbose_name_plural': 'ContentFile Indexes',
            },
        ),
        migrations.AddField(
            model_name='contentfile',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.document'),
        ),
        migrations.CreateModel(
            name='MembershipRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approve_datetime', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_request_approver', to=settings.AUTH_USER_MODEL)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_request_from_user', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.project')),
            ],
            options={
                'verbose_name': 'Membership Request',
                'verbose_name_plural': 'Membership Requests',
                'unique_together': {('from_user', 'project')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.folder')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.profile')),
            ],
            options={
                'verbose_name': 'Favorite Folder',
                'verbose_name_plural': 'Favorite Folders',
                'ordering': ['profile'],
                'unique_together': {('folder', 'profile')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.document')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.profile')),
            ],
            options={
                'verbose_name': 'Favorite Document',
                'verbose_name_plural': 'Favorite Documents',
                'ordering': ['profile'],
                'unique_together': {('document', 'profile')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='contentfile',
            unique_together={('file', 'version', 'parent')},
        ),
    ]
