# Generated by Django 3.2.14 on 2022-08-09 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repo_custom', '0001_initial'),
        ('repo', '0002_alter_project_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritedocument',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo_custom.document'),
        ),
    ]
