# Generated by Django 3.2.14 on 2022-08-09 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0003_alter_favoritedocument_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritedocument',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.document'),
        ),
    ]
