# Generated by Django 3.2.14 on 2022-08-09 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0004_alter_favoritedocument_document'),
        ('repo_custom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='repo.document')),
                ('custom_field', models.CharField(blank=True, max_length=255, null=True, verbose_name='Custom Field')),
            ],
            options={
                'abstract': False,
            },
            bases=('repo.document',),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
